# Generated by Django 6.1.1 on 2026-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_done_column',
            field=models.BooleanField(default=False),
        ),
    ]
